### ISSUE TITLE
is dohproxy support rubyfish DNS?

### ISSUE THREAD

**Issue by kbj** [major1201/dohproxy#2]
i change the address of  `doh-post` or `doh-get` type to `https://dns.rubyfish.cn/dns-query`, but it can't work successfully, the error message:
```
2018-12-10T18:05:19.155+0800    WARN    answer  dohproxy/upstream.go:151        doh resp err    {"id": 6323, "error": "Get https://dns.rubyfish.cn/dns-query?dns=GLMBAAABAAAAAAAAAnEzBXFsb2dvAmNuAAABAAE=: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
```
is my configuration wrong?

in addition, what's the meaning of the `fqdn` rule format?

thanks !

**Comment by major1201** [comment]
Hi, thank you for issuing!

1. `doh-get` didn't handle well, I've fixed it in the latest commit.
2. I've tested rubyfish, it works well with `doh-post`, could you test it again and paste the entire config file and log?
3. [`fqdn`](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) tag means domain in your config file matches the query domain exactly.

I'll release a new version after you've checked the `doh-post` method.

**Comment by kbj** [comment]
hello, thank you for your response!

I know where my mistake is

bacause i don't know the meaning of `fqdn` tag before, so i don't  specify the `fqdn` tag for rubyfish's domain. 

after set the `fqdn` tag, the `doh-post` for rubyfish can work well!

thanks very much!   
i'll close this issuse.
