### ISSUE TITLE
一段时间之后出现大量 socket: too many open files

### ISSUE THREAD

**Issue by KiokuCoder** [major1201/dohproxy#4]
怀疑`handler.go`下面`w dns.ResponseWriter`没有关闭导致。

**Comment by major1201** [comment]
> 
> 
> 怀疑`handler.go`下面`w dns.ResponseWriter`没有关闭导致。

感谢你的 issue
我确实在 Mac OS 上碰到过这个问题，请问下你发现问题的平台是？
代码已经修改，我会测试一天后提交并 release。

**Comment by KiokuCoder** [comment]
@major1201 ubuntu 16
